services:
  db:
    image: mysql:8.0.31
    env_file:
      - .env
    networks:
      - back-net
    # ports:
    #   - '3306:3306'
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
    volumes:
      - ./mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3306" ]
      interval: 3s
      timeout: 30s
      retries: 10
  backend:
    build: .
    platform: linux/amd64
    image: cineallo-backend
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - back-net
    ports:
      - "${CINEALLO_PORT}:3000"

networks:
  back-net:
